doctrine:
    dbal:
        default_connection: cardsmile
        connections:
            cardsmile:
#                dbname: cardsmile
#                user: postgres
#                password: root
#                host: 172.17.0.1
#                server_version: 13
                url: "pgsql://postgres:root@postgres:5432/cardsmile?serverVersion=13&charset=utf8"
                driver:   pdo_pgsql
            cardsmile_personal:
                url: "pgsql://postgres:root@postgres:5432/cardsmile_personal?serverVersion=13&charset=utf8"
                driver:   pdo_pgsql
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#        auto_mapping: true
        default_entity_manager: cardsmile
        entity_managers:
            cardsmile:
                connection: cardsmile
                mappings:
                    cardsmile:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Cardsmile'
                        prefix: 'App\Entity\Cardsmile'
                        alias: cardsmile
            cardsmile_personal:
                connection: cardsmile_personal
                mappings:
                    Customer:
                        type: yml
                        dir: '%kernel.project_dir%/src/Entity/doctrine_orm'
                        prefix: 'App\Entity\CardsmilePersonal'
                        is_bundle: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
