#controllers:
#    resource: ../src/Controller/
#    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

blog_list:
    path: /test
    controller: App\Infrastructure\Controller\ProductController::list

blog:
    path: /blog
    controller: App\Infrastructure\Controller\PriceController::list

app_lucky_number:
    path: /lucky/number
    controller: App\Infrastructure\Controller\LuckyController::number
    methods: POST
    #condition:  "context.getMethod() in ['POST', 'GET'] and request.headers.get('User-Agent') matches '/firefox/i'"

blog_show:
    path: /blog/list/{page}
    controller: App\Infrastructure\Controller\BlogController::list
    defaults:
        page: 1
    requirements:
        page: '1|2'

cache:
    path: /cache
    controller: App\Infrastructure\Controller\CacheHttpController::index
    methods: GET
#    stateless: true

generate_url2:
    path: /generate
    controller: App\Infrastructure\Controller\GenerateUrlController::index
    methods: GET