#controllers:
#    resource: ../src/Controller/
#    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

blog_list:
    path: /test
    controller: App\Infrastructure\Controller\Router\ProductController::list

blog:
    path: /blog
    controller: App\Infrastructure\Controller\Router\PriceController::list

app_lucky_number:
    path: /lucky/number
    controller: App\Infrastructure\Controller\Router\LuckyController::number
    methods: POST
    #condition:  "context.getMethod() in ['POST', 'GET'] and request.headers.get('User-Agent') matches '/firefox/i'"

blog_show:
    path: /blog/list/{page}
    controller: App\Infrastructure\Controller\Router\BlogController::list
    defaults:
        page: 1
    requirements:
        page: '1|2'

cacheHttp:
    path: /cache/http
    controller: App\Infrastructure\Controller\Router\CacheHttpController::index
    methods: GET
#    stateless: true

generate_url2:
    path: /generate
    controller: App\Infrastructure\Controller\Router\GenerateUrlController::index
    methods: GET

flash:
    path: /flash
    controller: App\Infrastructure\Controller\Controller\FlashController::index
    methods: GET

cookie:
    path: /cookie
    controller: App\Infrastructure\Controller\Controller\CookieController::index
    methods: GET

kernelq:
    path: /kernelq
    controller: App\Infrastructure\Controller\Request\RequestController::index
    methods: [GET, POST]

doctrine:
    path: /doctrine
    controller: App\Infrastructure\Controller\Controller\DoctrineController::index
    methods: [GET, POST]

session:
    path: /session
    controller: App\Infrastructure\Controller\Controller\SessionController::index
    methods: [GET, POST]

cache:
    path: /cache
    controller: App\Infrastructure\Controller\Controller\CacheController::index
    methods: [GET, POST]

logger:
    path: /logger
    controller: App\Infrastructure\Controller\Controller\LoggerController::index
    methods: [GET, POST]

nullObject:
    path: /nullObject
    controller: App\Infrastructure\Controller\Controller\NullController::index
    methods: [GET, POST]

swagger:
    path: /swagger
    controller: App\Infrastructure\Controller\Controller\SwaggerController::index
    methods: [GET, POST]