#controllers:
#    resource: ../src/Controller/
#    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

blog_list:
    path: /test
    controller: App\Infrastructure\Controller\ProductController::list

blog:
    path: /blog
    controller: App\Infrastructure\Controller\PriceController::list

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number