controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

blog_list:
    path: /test
    controller: App\Controller\ProductController::list